apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovn4nfv-deployment-2-annotation
  labels:
    app: ovn4nfv-2-annotation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ovn4nfv-2-annotation
  template:
    metadata:
      labels:
        app: ovn4nfv-2-annotation
      annotations:
        k8s.plugin.opnfv.org/nfn-network: '{ "type": "ovn4nfv", "interface": [{ "name": "ovn-port-net", "interface": "net0" , "defaultGateway": "false"},
                      { "name": "ovn-priv-net", "interface": "net1" , "defaultGateway": "false"}]}'
    spec:
      containers:
      - name: ovn4nfv-deployment-2-annotation
        image: "busybox"
        command: ["top"]
        stdin: true
        tty: true
